//#pragma src
//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// USER INCLUDES
#include "main.h"
#include "gen.h"
#include "button.h"

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
// enters interrupt every 1ms
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
  {
    // advance delay timer
    if(delay_on)
      {
        if(tmp_millis!=0)
          { tmp_millis--;}
        else
          { delay_on=0;}
      }

    TMR2CN0_TF2H = 0;
  }
//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR Content goes here. Remember to clear flag bits:
// TCON::TF0 (Timer 0 Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
  {
    TCON_TF0=0;
    buttoncntr++;
    buttonstate = BUT_PRESSED;
  }

//-----------------------------------------------------------------------------
// INT1_ISR
//-----------------------------------------------------------------------------
//
// INT1 ISR Content goes here. Remember to clear flag bits:
// TCON::IE1 (External Interrupt 1)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (INT1_ISR, INT1_IRQn)
  {
    if(buttoncntr>161){ // about 5 seconds
        buttonstate = BUT_LONGPRESS;
    }else if(buttoncntr>3){
        buttonstate = BUT_SHORTPRESS;
    }
    buttoncntr=0;
  }

