//#pragma src
//=========================================================
// src/EFM8BB31F32I-C-QFP32_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// Button logic
// short press - fix/release values
// long press (5sec) - calibration. It will cycle from 0EC til 5EC. Release button when desired calibration is found. 
//  Then insert the probe into calibration liquid and wait until it will say, "OK".

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include "main.h"
#include "InitDevice.h"
#include "gen.h"
#include "i2c.h"
#include "SSD1306.h"
#include "bat.h"
#include "probe.h"
#include "button.h"

volatile glob_t glob;
volatile calib_t calib_data[6];

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();

  buttonstate = BUT_NOTPRESSED;
  glob.displaystate = DISPLAY_EC;
  glob.calibselection = 0;

#ifdef DEBUGUART
	prnUART("START",1);
#endif

  delay_ms(100); // need for ssd1306 init
  ssd1306_init();
  ssd1306_clear_display();
  ssd1306_send_command(SSD1306_DISPLAYON);
  //ssd1306_printBitmap(0,1,57,2,calib_bitmap);


	while(1){
	    int16_t bat = getBatVoltageMv();
	    int16_t probe = GetProbeADC();
      if(bat<BATMINVOLTAGE){
          // do we at minimal or critical voltage?
          if(bat<BATCRITICALVOLTAGE){
			  if(glob.displaystate!=DISPLAY_CRITICALBAT) ssd1306_clear_display();
			  glob.displaystate=DISPLAY_CRITICALBAT;
              ssd1306_printBitmap(1,1,126,2,batCritical_bitmap);
          }else{
			  if(glob.displaystate!=DISPLAY_LOWBAT) ssd1306_clear_display();
			  glob.displaystate=DISPLAY_LOWBAT;
              ssd1306_printBitmap(20,1,87,2,batLow_bitmap);
          }
      }else{
		if(glob.displaystate!=DISPLAY_EC) ssd1306_clear_display();
		glob.displaystate=DISPLAY_EC;
		ssd1306_printBitmap(0,0,33,4,EC_bitmap);
        probe = getButtonState();
        ssd1306_printNumber(probe*100+glob.calibselection);
	    }
      delay_ms(1000);
	}

}
