//#pragma src
//=========================================================
// src/EFM8BB31F32I-C-QFP32_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include "main.h"
#include "InitDevice.h"
#include "i2c.h"
#include "SSD1306.h"

volatile uint16_t tmp_millis;
volatile bit delay_on;

void delay_ms(uint16_t ms_count)
 {
  tmp_millis = ms_count;
  delay_on = 1;
  while(delay_on);
 }

void pinsHighZ(void){
  P1MDOUT = 0;

  P1MDIN = P1MDIN_B0__ANALOG | P1MDIN_B1__ANALOG | P1MDIN_B2__DIGITAL
      | P1MDIN_B3__DIGITAL | P1MDIN_B4__DIGITAL | P1MDIN_B5__DIGITAL
      | P1MDIN_B6__DIGITAL;
}

void pinsPushPull(void){
  P1MDOUT = P1MDOUT_B0__PUSH_PULL | P1MDOUT_B1__PUSH_PULL
      | P1MDOUT_B2__OPEN_DRAIN | P1MDOUT_B3__OPEN_DRAIN | P1MDOUT_B4__OPEN_DRAIN
      | P1MDOUT_B5__OPEN_DRAIN | P1MDOUT_B6__OPEN_DRAIN;

  P1MDIN = P1MDIN_B0__DIGITAL | P1MDIN_B1__DIGITAL | P1MDIN_B2__DIGITAL
      | P1MDIN_B3__DIGITAL | P1MDIN_B4__DIGITAL | P1MDIN_B5__DIGITAL
      | P1MDIN_B6__DIGITAL;
}


//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {
  int16_t counter, adcval;
  int32_t sum1, sum2;
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
#ifdef DEBUGUART
	prnUART("START",1);
#endif

	delay_ms(100); // need for ssd1306 init
	ssd1306_init();
  ssd1306_clear_display();
  ssd1306_send_command(SSD1306_DISPLAYON);
//  ssd1306_print_uSv();


	while(1){
	    sum1=0;
      sum2=0;
	    adcval=0;
	    pinsPushPull();
	    PIN_1 = 1;
      PIN_2 = 0;
      ADC0CN0_ADINT = 0;  // reset ADC complete interrupt
      ADC0CN0_ADBUSY = 1; // start ADC conversions
	    for(counter=0;counter<500;counter++){
	        while(ADC0CN0_ADINT==0); // wait for adc to complete
	        adcval = ADC0;
          PIN_1 = !PIN_1;
          PIN_2 = !PIN_2;
          ADC0CN0_ADINT = 0;  // reset ADC complete interrupt
          ADC0CN0_ADBUSY = 1; // start ADC conversions
          sum1+=adcval;
          while(ADC0CN0_ADINT==0); // wait for adc to complete
          adcval = ADC0;
          PIN_1 = !PIN_1;
          PIN_2 = !PIN_2;
          ADC0CN0_ADINT = 0;  // reset ADC complete interrupt
          ADC0CN0_ADBUSY = 1; // start ADC conversions
          sum2+=adcval;
	    }
      pinsHighZ();
      sum1=sum1/500;
      sum2=4095-(sum2/500);

#ifdef DEBUGUART
      sendUART(sum1,0);
      prnUART(" ",0);
      sendUART(sum2,0);
      prnUART(" ",0);
      sendUART(sum1-(sum1-sum2)/2,1);
#endif
      ssd1306_printNumber(sum1-(sum1-sum2)/2);
      delay_ms(5000);
	}

}
